---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ vmname }}"
      template: "{{ template }}"
      datacenter: Datacenter
      folder: /
      state: poweredon
      networks:
        - name: VM Network
          ip: "{{ vmip }}"
          netmask: 255.255.255.0
          start_connected: True
      wait_for_ip_address: True
      customization:
        domain: "{{ domain }}"
        dns_servers:
          - "{{ dns1 }}"
        dns_suffix:
          - "{{ dnssearch }}"
    delegate_to: localhost

