---
- name: Removing VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Force remove
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ vmname }}"
      state: absent
      force: true

